version: "3.3"
volumes:
  shared-workspace:
    driver: local
  postgres-db-volume:
    driver: local
services:
  jupyterlab:
    image: stevenhurwitt/jupyterlab:latest
    container_name: yelp-jupyterlab
    environment:
      - JUPYTER_TOKEN=easy
    ports:
      - 8896:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./notebooks:/opt/workspace/notebooks
    read_only: false

  spark-master:
    image: stevenhurwitt/spark-master:latest
    container_name: yelp-spark-master
    hostname: spark-master
    ports:
      - 8079:8080
      - 7076:7077
      - 4039:4040
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: stevenhurwitt/spark-worker:latest
    container_name: yelp-spark-worker-1
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8192m
    ports:
      - 4045:4040
      - 8086:8081
      - 18083:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: stevenhurwitt/spark-worker:latest
    container_name: yelp-spark-worker-2
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8192m
    ports:
      - 4046:4040
      - 8087:8082
      - 18084:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  postgres:
    image: postgres
    container_name: yelp-postgres
    hostname: postgres
    ports: 
      - "5436:5432"
    environment: 
      - POSTGRES_USER=steven
      - POSTGRES_PASSWORD=Secret!1234
