version: "3.3"
secrets:
  aws_access_key_id: 
    file: aws_access_key.txt
  aws_secret_access_key: 
    file: aws_secret.txt
volumes:
  shared-workspace:
    driver: local
  postgres-db-volume:
    driver: local
services:
  jupyterlab:
    image: stevenhurwitt/jupyterlab:latest
    container_name: jupyterlab
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    environment:
      - JUPYTER_TOKEN=easy
      - AWS_ACCESS_KEY_ID=aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=aws_secret_access_key
    ports:
      - 8897:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./main:/opt/workspace/main
    read_only: false

  spark-master:
    image: stevenhurwitt/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: stevenhurwitt/spark-worker:latest
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4096m
    ports:
      - 4041:4040
      - 8083:8081
      - 18081:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: stevenhurwitt/spark-worker:latest
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4096m
    ports:
      - 4042:4040
      - 8082:8082
      - 18082:18080
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports: 
      - "5433:5432"
    environment: 
      - POSTGRES_USER=steven
      - POSTGRES_PASSWORD=Secret!1234
      